core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="File Manager API",
        default_version="v1",
        description="Test API for File Manager's File model",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="work.malekpour99@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("filemanager.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/api.json", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/filemanager/urls.py
from django.urls import path
from . import views

app_name = "filemanager"

urlpatterns = [
    path("", views.ContentView.as_view(), name="home"),
    path(
        "folder/<str:folder_slug>/", views.ContentView.as_view(), name="folder-content"
    ),
    path("upload/file/", views.FileUploadView.as_view(), name="upload-file"),
    path("create/folder/", views.FolderCreateView.as_view(), name="create-folder"),
    path("file/<int:pk>/edit/", views.FileUpdateView.as_view(), name="update-file"),
    path("file/<int:pk>/delete/", views.FileDeleteView.as_view(), name="delete-file"),
    path(
        "folder/<int:pk>/edit/", views.FolderUpdateView.as_view(), name="update-folder"
    ),
    path(
        "folder/<int:pk>/delete/",
        views.FolderDeleteView.as_view(),
        name="delete-folder",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

core/filemanager/models/base.py
from django.db import models


# Abstract Base Model
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

core/filemanager/models/files.py
from django.db import models
from django.conf import settings
from django.forms import ValidationError
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.utils.translation import gettext_lazy as _

import os
import logging
import mimetypes
from PIL import Image
from moviepy.video.io.VideoFileClip import VideoFileClip

from .base import BaseModel
from .folders import Folder

# Default Thumbnail for video files
DEFAULT_THUMBNAIL_PATH = os.path.join(
    settings.BASE_DIR, "static/img/default-video-thumbnail.png"
)

#
FILE_TYPE_CHOICES = [
    ("video", "Video"),
    ("image", "Image"),
]

# logger object
logger = logging.getLogger(__name__)


# File type custom validator
def validate_file_type(value):
    valid_mime_types = [
        "image/jpeg",
        "image/jpg",
        "image/png",
        "image/gif",
        "image/bmp",
        "image/tiff",
        "video/mp4",
        "video/mkv",
        "video/wmv",
        "video/mov",
        "video/avi",
        "video/mpeg",
        "video/quicktime",
        "video/x-msvideo",
        "video/x-ms-wmv",
    ]
    mime_type, encoding = mimetypes.guess_type(value.name)
    if mime_type not in valid_mime_types or mime_type is None:
        raise ValidationError(
            _("Unsupported file type. Only videos and images are supported.")
        )
    if mime_type and mime_type.startswith("image"):
        try:
            # Verify uploaded file is an image
            image = Image.open(value)
            image.verify()
        except Exception:
            raise ValidationError(
                _("Unsupported file type. Your file is not a valid image.")
            )
    if mime_type and mime_type.startswith("video"):
        try:
            # Verify uploaded file is a video
            clip = VideoFileClip(value.temporary_file_path())
            clip.reader.close()  # Close the reader
        except Exception:
            raise ValidationError(
                _("Unsupported file type. Your file is not a valid video.")
            )


# File size custom validator
def validate_file_size(value):
    max_size_mb = 7
    if value.size > max_size_mb * 1024 * 1024:
        raise ValidationError(
            _("File size exceeds the maximum limit of %(max_size_mb)d MB"),
            params={"max_size_mb": max_size_mb},
        )


# Model
class File(BaseModel):
    name = models.CharField(max_length=255, blank=True)
    file = models.FileField(
        upload_to="uploads/", validators=[validate_file_type, validate_file_size]
    )
    type = models.CharField(max_length=10, choices=FILE_TYPE_CHOICES)
    size = models.PositiveIntegerField(blank=True)
    thumbnail = models.ImageField(upload_to="thumbnails/", null=True, blank=True)
    folder = models.ForeignKey(
        Folder, on_delete=models.CASCADE, related_name="files", null=True, blank=True
    )
    owner = models.ForeignKey(
        "accounts.Profile", on_delete=models.CASCADE, related_name="files"
    )

    @property
    def formatted_size(self):
        """
        Returns the file size in human-readable format.
        """
        size = self.size
        if size < 1024:
            return "%d B" % size
        elif size < 1024 * 1024:
            return "%.1f KB" % (size / 1024)
        else:
            return "%.1f MB" % (size / (1024 * 1024))

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = os.path.basename(self.file.name)
        if not self.size:
            self.size = self.file.size
        if not self.type:
            self.type = self.choose_file_type()
        super().save(*args, **kwargs)
        if not self.thumbnail:
            self.create_thumbnail()

    def choose_file_type(self):
        mime_type, _ = mimetypes.guess_type(self.file.name)
        if mime_type.startswith("image"):
            return "image"
        elif mime_type.startswith("video"):
            return "video"

    def create_thumbnail(self):
        mime_type, _ = mimetypes.guess_type(self.file.name)
        if mime_type and mime_type.startswith("image"):
            self.create_image_thumbnail()
        elif mime_type and mime_type.startswith("video"):
            self.create_video_thumbnail()

    def create_image_thumbnail(self):
        thumbnail_size = (100, 100)
        image = Image.open(self.file)
        image.thumbnail(thumbnail_size, Image.LANCZOS)
        thumbnail_folder = "media/thumbnails"
        os.makedirs(thumbnail_folder, exist_ok=True)
        thumbnail_dir = "thumbnails"
        thumbnail_filename = os.path.basename(self.file.name)
        thumbnail_path = os.path.join(thumbnail_dir, thumbnail_filename)
        thumbnail_full_path = os.path.join("media/", thumbnail_path)
        image.save(thumbnail_full_path)
        self.thumbnail = thumbnail_path
        self.save()

    def create_video_thumbnail(self):
        thumbnail_size = (100, 100)
        thumbnail_folder = "media/thumbnails"
        os.makedirs(thumbnail_folder, exist_ok=True)
        thumbnail_dir = "thumbnails"
        thumbnail_filename = os.path.basename(self.file.name)
        thumbnail_path = os.path.join(thumbnail_dir, thumbnail_filename + ".jpg")
        thumbnail_full_path = os.path.join("media/", thumbnail_path)
        file_path = self.file.path
        try:
            clip = VideoFileClip(file_path)
            frame = clip.get_frame(1)  # Capture frame at 1 second
            clip.close()

            thumbnail = Image.fromarray(frame)
            thumbnail.thumbnail(thumbnail_size)

            thumbnail.save(thumbnail_full_path)

            self.thumbnail = thumbnail_path
            self.save()
        except Exception as error:
            logger.error(
                f"Failed to create thumbnail for video {self.file.name}: {error}"
            )
            self.thumbnail = DEFAULT_THUMBNAIL_PATH
            self.save()

    class Meta:
        unique_together = ("name", "folder", "owner")


@receiver(post_delete, sender=File)
def delete_file_on_model_delete(sender, instance, **kwargs):
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)
    if instance.thumbnail:
        if os.path.isfile(instance.thumbnail.path):
            os.remove(instance.thumbnail.path)

core/filemanager/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.http import is_safe_url
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView
from django.db.models import Q

from .models import File, Folder
from accounts.models import Profile


class ContentView(LoginRequiredMixin, View):
    """
    Showing list of files and folders for the authenticated owner
    """

    def get(self, request, *args, **kwargs):
        folder_slug = self.kwargs.get("folder_slug", None)
        files = File.objects.filter(
            Q(owner__user__id=self.request.user.id) & Q(folder__slug=folder_slug)
        ).order_by("name")
        folders = Folder.objects.filter(
            Q(owner__user__id=self.request.user.id) & Q(parent_folder__slug=folder_slug)
        ).order_by("name")
        if folder_slug:
            current_folder = Folder.objects.get(slug=folder_slug)
            folder_path = "home / " + current_folder.get_nested_path()
        else:
            current_folder = None
            folder_path = "home"
        context = {
            "files": files,
            "folders": folders,
            "current_folder": current_folder,
            "folder_path": folder_path,
            "folder_slug": folder_slug,
        }
        return render(request, "filemanager/content-list.html", context)


class FileUploadView(LoginRequiredMixin, CreateView):
    """
    Uploading a new file and dedicating this file to the current user
    """

    template_name = "filemanager/content-list.html"
    model = File
    fields = ["file", "folder"]

    def form_valid(self, form):
        form.instance.owner = Profile.objects.get(user__id=self.request.user.id)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url and is_safe_url(
            url=referer_url, allowed_hosts={self.request.get_host()}
        ):
            context["referer_url"] = referer_url
        else:
            context["referer_url"] = reverse_lazy("filemanager:home")
        return context

    def get_success_url(self):
        # Redirecting user to the last page
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        # fall back if referer_url was not available
        return reverse_lazy("filemanager:home")


class FolderCreateView(LoginRequiredMixin, CreateView):
    """
    Creating a new folder and dedicating this file to the current user
    """

    template_name = "filemanager/content-list.html"
    model = Folder
    fields = ["name", "parent_folder"]

    def form_valid(self, form):
        form.instance.owner = Profile.objects.get(user__id=self.request.user.id)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url and is_safe_url(
            url=referer_url, allowed_hosts={self.request.get_host()}
        ):
            context["referer_url"] = referer_url
        else:
            context["referer_url"] = reverse_lazy("filemanager:home")
        return context

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class FileUpdateView(LoginRequiredMixin, UpdateView):
    """
    Updating a file's name
    """

    template_name = "filemanager/content-list.html"
    fields = ["name"]

    def get_queryset(self):
        return File.objects.filter(owner__user__id=self.request.user.id)

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            return JsonResponse({"new_name": form.instance.name})
        return response

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class FileDeleteView(LoginRequiredMixin, DeleteView):
    """
    Deleting specified file
    """

    template_name = "filemanager/content-list.html"

    def get_queryset(self):
        return File.objects.filter(owner__user__id=self.request.user.id)

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class FolderUpdateView(LoginRequiredMixin, UpdateView):
    """
    Updating a folder's name
    """

    template_name = "filemanager/content-list.html"
    fields = ["name"]

    def get_queryset(self):
        return Folder.objects.filter(owner__user__id=self.request.user.id)

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            return JsonResponse({"new_name": form.instance.name})
        return response

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class FolderDeleteView(LoginRequiredMixin, DeleteView):
    """
    Deleting specified folder
    """

    template_name = "filemanager/content-list.html"

    def get_queryset(self):
        return Folder.objects.filter(owner__user__id=self.request.user.id)

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class SearchView(LoginRequiredMixin, View):
    """
    Searching files and folders for the authenticated owner
    """

    def get(self, request, *args, **kwargs):
        search_query = self.request.GET.get("search", "")
        files = File.objects.filter(
            Q(owner__user__id=self.request.user.id) & Q(name__contains=search_query)
        ).order_by("name")
        folders = Folder.objects.filter(
            Q(owner__user__id=self.request.user.id) & Q(name__contains=search_query)
        ).order_by("name")
        search_title = "Search results for: " + '"' + search_query + '"'
        context = {
            "search_title": search_title,
            "files": files,
            "folders": folders,
        }
        return render(request, "filemanager/search-list.html", context)

core/templates/filemanager/includes/delete-file-modal.html
<!-- Delete File Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete File</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete the file <strong id="file-name"></strong>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <form method="post" id="delete-form" action="">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

core/templates/filemanager/includes/delete-folder-modal.html
<!-- Delete Folder Modal -->
<div class="modal fade" id="deleteFolderModal" tabindex="-1" aria-labelledby="deleteFolderModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteFolderModalLabel">Delete Folder</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete the folder <strong id="folder-name"></strong>?
        <p class="text-danger mb-0">All files and folders inside this folder will be deleted too!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <form method="post" id="delete-folder-form" action="">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

core/templates/filemanager/includes/file-details-modal.html
<!-- File Details Modal -->
<div class="modal fade" id="fileDetailsModal" tabindex="-1" aria-labelledby="fileDetailsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="fileDetailsModalLabel">File Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-12 text-center mb-2" id="media-container">
            <!-- Video or Image tag will be dynamically added here -->
          </div>
          <div class="col-12">
            <p>
              <strong>Name:</strong> <span id="file-name"></span>
            </p>
            <p>
              <strong>Size:</strong> <span id="file-size"></span>
            </p>
            <p>
              <strong>Owner:</strong> <span id="file-owner"></span>
            </p>
            <p>
              <strong>Folder:</strong> <span id="file-folder"></span>
            </p>
            <p>
              <strong>Upload Date:</strong> <span id="file-upload-date"></span>
            </p>
            <p>
              <strong>Modified Date:</strong> <span id="file-modified-date"></span>
            </p>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

core/templates/filemanager/includes/modals-scripts.html
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const renameFileForm = document.getElementById('rename-file-form');
  
    renameFileForm.addEventListener('submit', function (event) {
      event.preventDefault(); // Prevent the default form submission
  
      const formData = new FormData(renameFileForm);
      const fileId = renameFileForm.action.split('/').slice(-3, -2)[0]; // Extract file ID from form action URL
  
      fetch(renameFileForm.action, {
        method: 'POST',
        headers: {
          'X-Requested-With': 'XMLHttpRequest', // Identify the request as AJAX
        },
        body: formData
      })
      .then(response => {
        if (response.ok) {
          return response.json();
        } else {
          throw new Error('Error renaming file');
        }
      })
      .then(data => {
        // Update the file name in the table
        const fileNameCell = document.querySelector(`div[id="file-${fileId}"]`);
        fileNameCell.textContent = data.new_name;
  
        // Close the modal
        const renameFileModal = bootstrap.Modal.getInstance(document.getElementById('renameFileModal'));
        renameFileModal.hide();
      })
      .catch(error => {
        console.error('Error:', error);
      });
    });
  
    const renameFileModal = document.getElementById('renameFileModal');
    renameFileModal.addEventListener('show.bs.modal', function (event) {
      const button = event.relatedTarget;
      const fileId = button.getAttribute('data-file-id');
      const fileName = button.getAttribute('data-file-name');
      const modalFileName = renameFileModal.querySelector('#file-name');
      const renameForm = renameFileModal.querySelector('#rename-file-form');
  
      modalFileName.value = fileName;
      renameForm.action = "{% url 'filemanager:update-file' pk=0 %}".replace('0', fileId);
    });
  });

    const deleteModal = document.getElementById('deleteModal')
    deleteModal.addEventListener('show.bs.modal', function (event) {
      const button = event.relatedTarget
      const fileId = button.getAttribute('data-file-id')
      const fileName = button.getAttribute('data-file-name')
      const modalFileName = deleteModal.querySelector('#file-name')
      const deleteForm = deleteModal.querySelector('#delete-form')
    
      modalFileName.textContent = fileName
      deleteForm.action = "{% url 'filemanager:delete-file' pk=0 %}".replace('0', fileId)
    });

  document.addEventListener('DOMContentLoaded', function () {
    const renameFolderForm = document.getElementById('rename-folder-form');
  
    renameFolderForm.addEventListener('submit', function (event) {
        event.preventDefault(); // Prevent the default form submission

        const formData = new FormData(renameFolderForm);
        const folderId = renameFolderForm.action.split('/').slice(-3, -2)[0]; // Extract folder ID from form action URL

        fetch(renameFolderForm.action, {
            method: 'POST',
            headers: {
                'X-Requested-With': 'XMLHttpRequest', // Identify the request as AJAX
            },
            body: formData
        })
        .then(response => {
            if (response.ok) {
                return response.json();
            } else {
                throw new Error('Error renaming folder');
            }
        })
        .then(data => {
            // Update the folder name in the table
            const folderNameCell = document.querySelector(`div[id="folder-${folderId}"]`);
            folderNameCell.textContent = data.new_name;

            // Close the modal
            const renameFolderModal = bootstrap.Modal.getInstance(document.getElementById('renameFolderModal'));
            renameFolderModal.hide();
        })
        .catch(error => {
            console.error('Error:', error);
        });
    });

    const renameFolderModal = document.getElementById('renameFolderModal')
    renameFolderModal.addEventListener('show.bs.modal', function (event) {
      const button = event.relatedTarget
      const folderId = button.getAttribute('data-folder-id')
      const folderName = button.getAttribute('data-folder-name')
      const modalFolderName = renameFolderModal.querySelector('#folder-name')
      const renameForm = renameFolderModal.querySelector('#rename-folder-form')
      
      modalFolderName.value = folderName
      renameForm.action = "{% url 'filemanager:update-folder' pk=0 %}".replace('0', folderId)
    });
  });
    
    const deleteFolderModal = document.getElementById('deleteFolderModal')
    deleteFolderModal.addEventListener('show.bs.modal', function (event) {
      const button = event.relatedTarget
      const folderId = button.getAttribute('data-folder-id')
      const folderName = button.getAttribute('data-folder-name')
      const modalFolderName = deleteFolderModal.querySelector('#folder-name')
      const deleteFolderForm = deleteFolderModal.querySelector('#delete-folder-form')
    
      modalFolderName.textContent = folderName
      deleteFolderForm.action = "{% url 'filemanager:delete-folder' pk=0 %}".replace('0', folderId)
    });
    
    var fileDetailsModal = document.getElementById('fileDetailsModal')
    fileDetailsModal.addEventListener('show.bs.modal', function (event) {
      var button = event.relatedTarget
      var modal = this
      var mediaContainer = modal.querySelector('#media-container')
      var fileType = button.getAttribute('data-file-type')
      var fileUrl = button.getAttribute('data-file-url')
      var fileName = button.getAttribute('data-file-name')
      var fileSize = button.getAttribute('data-file-size')
      var fileOwner = button.getAttribute('data-file-owner')
      var fileFolder = button.getAttribute('data-file-folder')
      var fileUploadDate = button.getAttribute('data-file-upload-date')
      var fileModifiedDate = button.getAttribute('data-file-modified-date')
    
      if (fileType == 'video') {
        mediaContainer.innerHTML = '<video controls style="max-width: 100%; max-height: 100%;"><source src="' + fileUrl + '" type="video/mp4">Your browser does not support the video tag.</video>'
      } else {
        mediaContainer.innerHTML = '<img src="' + fileUrl + '" alt="' + fileName + '" style="max-width: 100%; max-height: 100%;">'
      }
    
      modal.querySelector('#file-name').textContent = fileName
      modal.querySelector('#file-size').textContent = fileSize
      modal.querySelector('#file-owner').textContent = fileOwner
      modal.querySelector('#file-folder').textContent = fileFolder
      modal.querySelector('#file-upload-date').textContent = fileUploadDate
      modal.querySelector('#file-modified-date').textContent = fileModifiedDate
    });
</script>

core/templates/filemanager/includes/rename-file-modal.html
<!-- Rename File Modal -->
<div class="modal fade" id="renameFileModal" tabindex="-1" aria-labelledby="renameFileModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="renameFileModalLabel">Rename File</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="post" id="rename-file-form">
        {% csrf_token %}
        <div class="modal-body">
          <div class="mb-3">
            <label for="file-name" class="form-label">New File Name</label>
            <input type="text" class="form-control" id="file-name" name="name" required />
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Rename</button>
        </div>
      </form>
    </div>
  </div>
</div>

core/templates/filemanager/includes/rename-folder-modal.html
<!-- Rename Folder Modal -->
<div class="modal fade" id="renameFolderModal" tabindex="-1" aria-labelledby="renameFolderModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="renameFolderModalLabel">Rename Folder</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="post" id="rename-folder-form">
        {% csrf_token %}
        <div class="modal-body">
          <div class="mb-3">
            <label for="folder-name" class="form-label">New Folder Name</label>
            <input type="text" class="form-control" id="folder-name" name="name" required />
            <p class="text-secondary mb-0 mt-1">Folder name can not contain invalid characters: @#%$*&<>?|/:</p>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </form>
    </div>
  </div>
</div>