core/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("api/v1/", include("accounts.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="File Manager API",
        default_version="v1",
        description="Test API for File Manager's File model",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="work.malekpour99@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("filemanager.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/api.json", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/filemanager/urls.py
from django.urls import path
from . import views

app_name = "filemanager"

urlpatterns = [
    path("", views.ContentView.as_view(), name="home"),
    path(
        "folder/<str:folder_slug>/", views.ContentView.as_view(), name="folder-content"
    ),
    path("upload/file/", views.FileUploadView.as_view(), name="upload-file"),
    path("create/folder/", views.FolderCreateView.as_view(), name="create-folder"),
    path("file/<int:pk>/edit/", views.FileUpdateView.as_view(), name="update-file"),
    path("file/<int:pk>/delete/", views.FileDeleteView.as_view(), name="delete-file"),
    path(
        "folder/<int:pk>/edit/", views.FolderUpdateView.as_view(), name="update-folder"
    ),
    path(
        "folder/<int:pk>/delete/",
        views.FolderDeleteView.as_view(),
        name="delete-folder",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

core/filemanager/models/base.py
from django.db import models


# Abstract Base Model
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>File Manager App</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    
    {% block css_links %} {% endblock css_links %}
  </head>
  <body class="vh-100" style="background-color: #eee;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/' %} active {% endif %}" 
                href="{% url 'filemanager:home' %}">Home</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/accounts/login/' %} active {% endif %}" 
                href="{% url 'accounts:login' %}">Login</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    
    <main>
      {% block main_content %} {% endblock main_content %}
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+CKAdT/8VCY7queRzjHTBS+apnPjgY6Oaq2zQ6w" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>