core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="File Manager API",
        default_version="v1",
        description="Test API for File Manager's File model",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="work.malekpour99@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("filemanager.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/api.json", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/filemanager/urls.py
from django.urls import path
from . import views

app_name = "filemanager"

urlpatterns = [
    path("", views.ContentView.as_view(), name="home"),
    path(
        "folder/<str:folder_slug>/", views.ContentView.as_view(), name="folder-content"
    ),
    path("upload/file/", views.FileUploadView.as_view(), name="upload-file"),
    path("create/folder/", views.FolderCreateView.as_view(), name="create-folder"),
    path("file/<int:pk>/edit/", views.FileUpdateView.as_view(), name="update-file"),
    path("file/<int:pk>/delete/", views.FileDeleteView.as_view(), name="delete-file"),
    path(
        "folder/<int:pk>/edit/", views.FolderUpdateView.as_view(), name="update-folder"
    ),
    path(
        "folder/<int:pk>/delete/",
        views.FolderDeleteView.as_view(),
        name="delete-folder",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

core/filemanager/models/base.py
from django.db import models


# Abstract Base Model
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

core/filemanager/models/files.py
from django.db import models
from django.conf import settings
from django.forms import ValidationError
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.utils.translation import gettext_lazy as _

import os
import logging
import mimetypes
from PIL import Image
from moviepy.video.io.VideoFileClip import VideoFileClip

from .base import BaseModel
from .folders import Folder

# Default Thumbnail for video files
DEFAULT_THUMBNAIL_PATH = os.path.join(
    settings.BASE_DIR, "static/img/default-video-thumbnail.png"
)

#
FILE_TYPE_CHOICES = [
    ("video", "Video"),
    ("image", "Image"),
]

# logger object
logger = logging.getLogger(__name__)


# File type custom validator
def validate_file_type(value):
    valid_mime_types = [
        "image/jpeg",
        "image/jpg",
        "image/png",
        "image/gif",
        "image/bmp",
        "image/tiff",
        "video/mp4",
        "video/mkv",
        "video/wmv",
        "video/mov",
        "video/avi",
        "video/mpeg",
        "video/quicktime",
        "video/x-msvideo",
        "video/x-ms-wmv",
    ]
    mime_type, encoding = mimetypes.guess_type(value.name)
    if mime_type not in valid_mime_types or mime_type is None:
        raise ValidationError(
            _("Unsupported file type. Only videos and images are supported.")
        )
    if mime_type and mime_type.startswith("image"):
        try:
            # Verify uploaded file is an image
            image = Image.open(value)
            image.verify()
        except Exception:
            raise ValidationError(
                _("Unsupported file type. Your file is not a valid image.")
            )
    if mime_type and mime_type.startswith("video"):
        try:
            # Verify uploaded file is a video
            clip = VideoFileClip(value.temporary_file_path())
            clip.reader.close()  # Close the reader
        except Exception:
            raise ValidationError(
                _("Unsupported file type. Your file is not a valid video.")
            )


# File size custom validator
def validate_file_size(value):
    max_size_mb = 7
    if value.size > max_size_mb * 1024 * 1024:
        raise ValidationError(
            _("File size exceeds the maximum limit of %(max_size_mb)d MB"),
            params={"max_size_mb": max_size_mb},
        )


# Model
class File(BaseModel):
    name = models.CharField(max_length=255, blank=True)
    file = models.FileField(
        upload_to="uploads/", validators=[validate_file_type, validate_file_size]
    )
    type = models.CharField(max_length=10, choices=FILE_TYPE_CHOICES)
    size = models.PositiveIntegerField(blank=True)
    thumbnail = models.ImageField(upload_to="thumbnails/", null=True, blank=True)
    folder = models.ForeignKey(
        Folder, on_delete=models.CASCADE, related_name="files", null=True, blank=True
    )
    owner = models.ForeignKey(
        "accounts.Profile", on_delete=models.CASCADE, related_name="files"
    )

    @property
    def formatted_size(self):
        """
        Returns the file size in human-readable format.
        """
        size = self.size
        if size < 1024:
            return "%d B" % size
        elif size < 1024 * 1024:
            return "%.1f KB" % (size / 1024)
        else:
            return "%.1f MB" % (size / (1024 * 1024))

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = os.path.basename(self.file.name)
        if not self.size:
            self.size = self.file.size
        if not self.type:
            self.type = self.choose_file_type()
        super().save(*args, **kwargs)
        if not self.thumbnail:
            self.create_thumbnail()

    def choose_file_type(self):
        mime_type, _ = mimetypes.guess_type(self.file.name)
        if mime_type.startswith("image"):
            return "image"
        elif mime_type.startswith("video"):
            return "video"

    def create_thumbnail(self):
        mime_type, _ = mimetypes.guess_type(self.file.name)
        if mime_type and mime_type.startswith("image"):
            self.create_image_thumbnail()
        elif mime_type and mime_type.startswith("video"):
            self.create_video_thumbnail()

    def create_image_thumbnail(self):
        thumbnail_size = (100, 100)
        image = Image.open(self.file)
        image.thumbnail(thumbnail_size, Image.LANCZOS)
        thumbnail_folder = "media/thumbnails"
        os.makedirs(thumbnail_folder, exist_ok=True)
        thumbnail_dir = "thumbnails"
        thumbnail_filename = os.path.basename(self.file.name)
        thumbnail_path = os.path.join(thumbnail_dir, thumbnail_filename)
        thumbnail_full_path = os.path.join("media/", thumbnail_path)
        image.save(thumbnail_full_path)
        self.thumbnail = thumbnail_path
        self.save()

    def create_video_thumbnail(self):
        thumbnail_size = (100, 100)
        thumbnail_folder = "media/thumbnails"
        os.makedirs(thumbnail_folder, exist_ok=True)
        thumbnail_dir = "thumbnails"
        thumbnail_filename = os.path.basename(self.file.name)
        thumbnail_path = os.path.join(thumbnail_dir, thumbnail_filename + ".jpg")
        thumbnail_full_path = os.path.join("media/", thumbnail_path)
        file_path = self.file.path
        try:
            clip = VideoFileClip(file_path)
            frame = clip.get_frame(1)  # Capture frame at 1 second
            clip.close()

            thumbnail = Image.fromarray(frame)
            thumbnail.thumbnail(thumbnail_size)

            thumbnail.save(thumbnail_full_path)

            self.thumbnail = thumbnail_path
            self.save()
        except Exception as error:
            logger.error(
                f"Failed to create thumbnail for video {self.file.name}: {error}"
            )
            self.thumbnail = DEFAULT_THUMBNAIL_PATH
            self.save()

    class Meta:
        unique_together = ("name", "folder", "owner")


@receiver(post_delete, sender=File)
def delete_file_on_model_delete(sender, instance, **kwargs):
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)
    if instance.thumbnail:
        if os.path.isfile(instance.thumbnail.path):
            os.remove(instance.thumbnail.path)

core/filemanager/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.http import is_safe_url
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView
from django.db.models import Q

from .models import File, Folder
from accounts.models import Profile


class ContentView(LoginRequiredMixin, View):
    """
    Showing list of files and folders for the authenticated owner
    """

    def get(self, request, *args, **kwargs):
        folder_slug = self.kwargs.get("folder_slug", None)
        files = File.objects.filter(
            Q(owner__user__id=self.request.user.id) & Q(folder__slug=folder_slug)
        ).order_by("name")
        folders = Folder.objects.filter(
            Q(owner__user__id=self.request.user.id) & Q(parent_folder__slug=folder_slug)
        ).order_by("name")
        if folder_slug:
            current_folder = Folder.objects.get(slug=folder_slug)
            folder_path = "home / " + current_folder.get_nested_path()
        else:
            current_folder = None
            folder_path = "home"
        context = {
            "files": files,
            "folders": folders,
            "current_folder": current_folder,
            "folder_path": folder_path,
            "folder_slug": folder_slug,
        }
        return render(request, "filemanager/content-list.html", context)


class FileUploadView(LoginRequiredMixin, CreateView):
    """
    Uploading a new file and dedicating this file to the current user
    """

    template_name = "filemanager/content-list.html"
    model = File
    fields = ["file", "folder"]

    def form_valid(self, form):
        form.instance.owner = Profile.objects.get(user__id=self.request.user.id)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url and is_safe_url(
            url=referer_url, allowed_hosts={self.request.get_host()}
        ):
            context["referer_url"] = referer_url
        else:
            context["referer_url"] = reverse_lazy("filemanager:home")
        return context

    def get_success_url(self):
        # Redirecting user to the last page
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        # fall back if referer_url was not available
        return reverse_lazy("filemanager:home")


class FolderCreateView(LoginRequiredMixin, CreateView):
    """
    Creating a new folder and dedicating this file to the current user
    """

    template_name = "filemanager/content-list.html"
    model = Folder
    fields = ["name", "parent_folder"]

    def form_valid(self, form):
        form.instance.owner = Profile.objects.get(user__id=self.request.user.id)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url and is_safe_url(
            url=referer_url, allowed_hosts={self.request.get_host()}
        ):
            context["referer_url"] = referer_url
        else:
            context["referer_url"] = reverse_lazy("filemanager:home")
        return context

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class FileUpdateView(LoginRequiredMixin, UpdateView):
    """
    Updating a file's name
    """

    template_name = "filemanager/content-list.html"
    fields = ["name"]

    def get_queryset(self):
        return File.objects.filter(owner__user__id=self.request.user.id)

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            return JsonResponse({"new_name": form.instance.name})
        return response

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class FileDeleteView(LoginRequiredMixin, DeleteView):
    """
    Deleting specified file
    """

    template_name = "filemanager/content-list.html"

    def get_queryset(self):
        return File.objects.filter(owner__user__id=self.request.user.id)

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class FolderUpdateView(LoginRequiredMixin, UpdateView):
    """
    Updating a folder's name
    """

    template_name = "filemanager/content-list.html"
    fields = ["name"]

    def get_queryset(self):
        return Folder.objects.filter(owner__user__id=self.request.user.id)

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            return JsonResponse({"new_name": form.instance.name})
        return response

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class FolderDeleteView(LoginRequiredMixin, DeleteView):
    """
    Deleting specified folder
    """

    template_name = "filemanager/content-list.html"

    def get_queryset(self):
        return Folder.objects.filter(owner__user__id=self.request.user.id)

    def get_success_url(self):
        referer_url = self.request.META.get("HTTP_REFERER")
        if referer_url:
            return referer_url
        return reverse_lazy("filemanager:home")


class SearchView(LoginRequiredMixin, View):
    """
    Searching files and folders for the authenticated owner
    """

    def get(self, request, *args, **kwargs):
        search_query = self.request.GET.get("search", "")
        files = File.objects.filter(
            Q(owner__user__id=self.request.user.id) & Q(name__contains=search_query)
        ).order_by("name")
        folders = Folder.objects.filter(
            Q(owner__user__id=self.request.user.id) & Q(name__contains=search_query)
        ).order_by("name")
        search_title = "Search results for: " + '"' + search_query + '"'
        context = {
            "search_title": search_title,
            "files": files,
            "folders": folders,
        }
        return render(request, "filemanager/search-list.html", context)

core/templates/filemanager/content-list.html
{% extends 'base.html' %}
{% load static %}

{% block css_links %}
  <style>
    tbody tr:hover td:hover {
      background-color: #f0f0f0 !important;
      cursor: pointer;
    }
    a {
      color: inherit;
      text-decoration: none;
    }
  </style>
{% endblock %}

{% block main_content %}
  <section class="h-100 w-100" style="background-color: #eee;">
    <div class="container py-2 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-12 col-xl-12">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <h4 class="text-center my-3 pb-3">File Manager App</h4>
              <div class="row text-center">
                {% if form.errors %}
                  {% for field in form %}
                    {% if field.errors %}
                      {% for error in field.errors %}
                        <p class="text-danger">{{ field.name|title }} - {{ error|escape }}</p>
                      {% endfor %}
                    {% endif %}
                  {% endfor %}
                {% endif %}
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="text-danger">{{ error|escape }}</p>
                    {% endfor %}
                {% endif %}
                {% if form.errors %}
                  <a href="{{ referer_url }}"><button type="button" class="btn btn-outline-secondary fs-3 mb-4">Click Here to return to previous page</button></a>
                {% endif %}
              </div>
              
              {% if not form.errors %}                
              <div class="row">
                <div class="col">
                  <form class="row g-1 text-center mb-2 pb-2" method="post" action="{% url 'filemanager:upload-file' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-9">
                      <div class="form-outline">
                        <input type="file" id="task-title" name="file" class="form-control" placeholder="Choose a file.." />
                        <input type="hidden" name="folder" class="form-control" value="{% if current_folder %} {{ current_folder.id }} {% endif %}"/>
                      </div>
                    </div>
                    <div class="d-grid col-3">
                      <button type="submit" class="btn btn-outline-primary">Upload</button>
                    </div>
                  </form>
                </div>
                <div class="col">
                  <form class="row g-1 text-center mb-1 pb-2" method="post" action="{% url 'filemanager:create-folder' %}">
                    {% csrf_token %}
                    <div class="col-9">
                      <div class="form-outline">
                        <input type="text" id="task-title" name="name" class="form-control" placeholder="New Folder Name" />
                        <input type="hidden" name="parent_folder" class="form-control" value="{% if current_folder %} {{ current_folder.id }} {% endif %}"/>
                      </div>
                    </div>
                    <div class="d-grid col-3">
                      <button type="submit" class="btn btn-outline-success">Create Folder</button>
                    </div>
                  </form>
                </div>
              </div>
              <hr />

              <div class="row mb-2">
                <div class="col-7">
                  <div class="card border border-3">
                    <div class="card-body">{{ folder_path }}</div>
                  </div>
                </div>
                <!-- Serach Bar -->
                <div class="col-5">
                  <form class="row g-1" method="get" action="{% url 'filemanager:search' %}">
                    <div class="col-10">
                      <div class="form-outline">
                        <input type="text" name="search" class="form-control p-3" placeholder="Search Files & Folders" />
                      </div>
                    </div>
                    <div class="col-2">
                      <button type="submit" class="btn btn-outline-secondary p-3 px-4"><i class="bi bi-search"></i></button>
                    </div>
                  </form>
                </div>
              </div>

              <hr />

              <table class="table mb-4">
                <thead>
                  <tr>
                    <th scope="col">Preview</th>
                    <th scope="col">Name</th>
                    <th scope="col">Size</th>
                    <th scope="col">Upload-Date</th>
                    <th scope="col" class="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% if current_folder %}
                    <tr>
                      <td class="col-1 text-center">
                        {% if current_folder.parent_folder.slug %}
                        <a href="{% url 'filemanager:folder-content' folder_slug=current_folder.parent_folder.slug %}">
                        {% else %}
                        <a href="{% url 'filemanager:home' %}">
                        {% endif %}
                          <img src="{% static 'img/return-icon.png' %}" alt="{{ current_folder.name }}" />
                        </a>
                      </td>
                      <td class="col-5">
                        {% if current_folder.parent_folder.slug %}
                        <a href="{% url 'filemanager:folder-content' folder_slug=current_folder.parent_folder.slug %}">
                        {% else %}
                        <a href="{% url 'filemanager:home' %}">
                        {% endif %}
                        <div>
                          <p>Return back</p>
                        </div>
                        </a>
                      </td>
                      <td class="col-2"></td>
                      <td class="col-2"></td>
                      <td class="col-2 text-center"></td>
                    </tr>
                  {% endif %}
                  {% for folder in folders %}
                    <tr>
                      <td class="col-1 text-center">
                        <a href="{% url 'filemanager:folder-content' folder_slug=folder.slug %}"><img src="{% static 'img/folder-icon.png' %}" alt="{{ folder.name }}" /></a>
                      </td>
                      <td class="col-5">
                        <a href="{% url 'filemanager:folder-content' folder_slug=folder.slug %}"><div id="folder-{{folder.id}}">{{ folder.name }}</div><p class="fw-light">{{ folder.owner }}</p></a>
                      </td>
                      <td class="col-2"></td>
                      <td class="col-2">{{ folder.created_at|date:'d M Y' }}</td>
                      <td class="col-2 text-center">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#renameFolderModal" data-folder-id="{{ folder.id }}" data-folder-name="{{ folder.name }}">
                          <i class="bi bi-pencil-square fs-5"></i>
                        </button>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteFolderModal" data-folder-id="{{ folder.id }}" data-folder-name="{{ folder.name }}">
                          <i class="bi bi-trash-fill fs-5"></i>
                        </button>
                      </td>
                    </tr>
                  {% endfor %}

                  {% for file in files %}
                    <tr data-bs-toggle="modal" data-bs-target="#fileDetailsModal" data-file-id="{{ file.id }}" data-file-url="{{ file.file.url }}" data-file-name="{{ file.name }}" data-file-type="{{ file.type }}" data-file-size="{{ file.formatted_size }}" data-file-owner="{{ file.owner }}" data-file-folder="{{ file.folder.name|default:'home' }}" data-file-upload-date="{{ file.created_at|date:'d M Y' }}" data-file-modified-date="{{ file.updated_at|date:'d M Y' }}">
                      <td class="col-1 text-center">
                        <img src="{{ file.thumbnail.url }}" alt="{{ file.name }}" />
                      </td>
                      <td class="col-5">
                        <div id="file-{{ file.id }}">{{ file.name }}</div><p class="fw-light">{{ file.owner }}</p>
                      </td>
                      <td class="col-2">{{ file.formatted_size }}</td>
                      <td class="col-2">{{ file.created_at|date:'d M Y' }}</td>
                      <td class="col-2 text-center">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#renameFileModal" data-file-id="{{ file.id }}" data-file-name="{{ file.name }}">
                          <i class="bi bi-pencil-square fs-5"></i>
                        </button>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" data-file-id="{{ file.id }}" data-file-name="{{ file.name }}">
                          <i class="bi bi-trash-fill fs-5"></i>
                        </button>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% endif %}
              {% if not folders and not files and not form.errors %}
              <div class="text-center fs-5">This folder is empty.</div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% include "filemanager/includes/file-details-modal.html" %}
  
  {% include "filemanager/includes/rename-file-modal.html" %}

  {% include "filemanager/includes/delete-file-modal.html" %}
  
  {% include "filemanager/includes/rename-folder-modal.html" %}
  
  {% include "filemanager/includes/delete-folder-modal.html" %}  
  
  {% include "filemanager/includes/modals-scripts.html" %}
  
{% endblock %}